/* Daily Plate v1.1 enhancements */
const DP_VERSION='1.1';
const DP_SCHEMA_VERSION=4;
const dpOriginalLoad=load;
const dpOriginalSave=save;
const dpOriginalAllIngredients=allIngredients;
const dpOriginalConfirmAddEntry=confirmAddEntry;
const dpOriginalRenderToday=renderToday;
const dpOriginalRenderLog=renderLog;
const dpOriginalRenderProfile=renderProfileScreen;
const dpOriginalRenderIngredients=renderIngredientLibrary;
const dpOriginalOpenQty=openQtySheet;
let dpEdit=null;

function dpId(prefix){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9)}
function dpSlug(v){return String(v||'food').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,60)}
function dpBuiltinId(i){return i.id||'food_'+dpSlug(i.name)}
function dpEscape(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dpMigrate(s){
 s=s&&typeof s==='object'?s:{};s.profile=s.profile||null;s.logs=s.logs||{};s.customIngredients=Array.isArray(s.customIngredients)?s.customIngredients:[];s.deletedBuiltins=Array.isArray(s.deletedBuiltins)?s.deletedBuiltins:[];
 s.favourites=Array.isArray(s.favourites)?s.favourites:[];s.recentIngredients=Array.isArray(s.recentIngredients)?s.recentIngredients:[];s.lastServings=s.lastServings||{};s.recipes=Array.isArray(s.recipes)?s.recipes:[];s.weights=Array.isArray(s.weights)?s.weights:[];s.settings=s.settings||{};
 s.deletedBuiltins=s.deletedBuiltins.map(id=>{if(/^b\d+$/.test(id)){const i=INGREDIENTS[Number(id.slice(1))];return i?dpBuiltinId(i):id}return id});
 s.customIngredients.forEach(i=>{i.id=i.id||dpId('custom');i.basis=i.basis||(i.isLiquid?'100ml':'100g')});
 Object.entries(s.logs).forEach(([date,day])=>MEALS.forEach(m=>{day[m.key]=Array.isArray(day[m.key])?day[m.key]:[];day[m.key].forEach(e=>{e.id=e.id||dpId('entry');e.quantity=Number(e.quantity||e.grams)||0;e.grams=Number(e.grams||e.quantity)||0;if(!e.ingredientId){const n=String(e.name||'').replace(/\s×\d+(\.\d+)?$/,'');const i=[...s.customIngredients,...INGREDIENTS].find(x=>x.name===n);e.ingredientId=i?(i.id||dpBuiltinId(i)):null}e.createdAt=e.createdAt||new Date(date+'T12:00:00').toISOString();e.updatedAt=e.updatedAt||e.createdAt})}));
 if(s.profile&&!s.weights.length&&Number(s.profile.weight)>0)s.weights.push({id:dpId('weight'),date:todayKey(),value:Number(s.profile.weight)});
 s.schemaVersion=DP_SCHEMA_VERSION;s.sync=s.sync||{enabled:false,deviceId:dpId('device'),lastModified:new Date().toISOString()};return s;
}
load=function(){try{STATE=dpMigrate(JSON.parse(localStorage.getItem('dp_state')||'{}'))}catch(e){STATE=dpMigrate({})}};
save=function(){try{const old=localStorage.getItem('dp_state');if(old)localStorage.setItem('dp_recovery',old);STATE.schemaVersion=DP_SCHEMA_VERSION;STATE.sync=STATE.sync||{};STATE.sync.lastModified=new Date().toISOString();localStorage.setItem('dp_state',JSON.stringify(STATE))}catch(e){toast('Unable to save data')}};
allIngredients=function(){const b=INGREDIENTS.map(i=>({...i,id:dpBuiltinId(i),basis:i.basis||(i.isLiquid?'100ml':'100g')})).filter(i=>!STATE.deletedBuiltins.includes(i.id));return [...STATE.customIngredients,...b]};
findIngredient=function(id){return allIngredients().find(i=>i.id===id)};
function dpNutrition(e){const i=e.ingredientId?findIngredient(e.ingredientId):null;if(!i)return e;const x=(Number(e.quantity||e.grams)||0)/100;return {...e,cal:i.cal*x,p:i.p*x,c:i.c*x,f:i.f*x,sugar:(i.sugar||0)*x,fiber:(i.fiber||0)*x,sodium:(i.sodium||0)*x}}
function dpTotals(k){const o={cal:0,p:0,c:0,f:0,sugar:0,fiber:0,sodium:0},d=getDayLog(k);MEALS.forEach(m=>(d[m.key]||[]).forEach(e=>{const n=dpNutrition(e);Object.keys(o).forEach(x=>o[x]+=Number(n[x])||0)}));return o}

confirmAddEntry=function(){const i=findIngredient(activeIngredientForQty);if(!i)return;const amount=qtyMode==='count'&&i.uw?qtyCount*i.uw:Number(document.getElementById('qty-grams').value);if(!(amount>0)){toast('Enter a valid amount');return}const x=amount/100,e={id:dpId('entry'),ingredientId:i.id,name:qtyMode==='count'&&i.uw?i.name+' ×'+qtyCount:i.name,quantity:amount,grams:Math.round(amount),unit:i.isLiquid?'ml':'g',cal:i.cal*x,p:i.p*x,c:i.c*x,f:i.f*x,sugar:(i.sugar||0)*x,fiber:(i.fiber||0)*x,sodium:(i.sodium||0)*x,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const k=editingLogDate||todayKey();getDayLog(k)[activeMealKey].push(e);STATE.lastServings[i.id]={amount,mode:qtyMode,count:qtyCount};STATE.recentIngredients=[i.id,...STATE.recentIngredients.filter(x=>x!==i.id)].slice(0,12);save();closeSheet('sheet-qty');toast('Added');editingLogDate?renderLogDayDetail(k):renderToday()};
openQtySheet=function(id){dpOriginalOpenQty(id);const x=STATE.lastServings[id],i=findIngredient(id);if(x&&i){if(x.mode==='count'&&i.uw){qtyMode='count';qtyCount=x.count||1;document.getElementById('qty-count-num').textContent=qtyCount}else{switchQtyMode('grams');document.getElementById('qty-grams').value=x.amount}updateQtyPreview()}};

renderToday=function(){Object.values(STATE.logs||{}).forEach(d=>MEALS.forEach(m=>(d[m.key]||[]).forEach((e,n)=>d[m.key][n]=dpNutrition(e))));dpOriginalRenderToday();if(!STATE.profile)return;const t=dpTotals(todayKey()),target=calcCalorieTarget(STATE.profile),diff=target-t.cal;document.getElementById('cal-remaining-sub').textContent=diff>=0?Math.round(diff)+' remaining':Math.abs(Math.round(diff))+' over';if(STATE.profile.carbTarget)setPill('carb',t.c,STATE.profile.carbTarget);if(STATE.profile.fatTarget)setPill('fat',t.f,STATE.profile.fatTarget);const h=document.getElementById('dp-today-extra');if(h){const ids=[...STATE.favourites,...STATE.recentIngredients].filter((x,n,a)=>a.indexOf(x)===n).slice(0,6);h.innerHTML='<button class="btn ember" onclick="dpQuickLog()">＋ Log food</button><div class="micro-grid"><div><b>'+Math.round(t.fiber)+'g</b><span>Fibre</span></div><div><b>'+Math.round(t.sugar)+'g</b><span>Sugar</span></div><div><b>'+Math.round(t.sodium)+'mg</b><span>Sodium</span></div></div><div class="section-title">Quick add</div><div class="quick-chips">'+(ids.map(id=>{const i=findIngredient(id);return i?'<button onclick="dpQuickAdd(\''+i.id+'\')">'+dpEscape(i.name)+'</button>':''}).join('')||'<span class="empty-hint">Recent and favourite foods appear here.</span>')+'</div>'}};
function dpMealNow(){const h=new Date().getHours();return h<10?'breakfast':h<15?'lunch':h<20?'dinner':'snacks'}
function dpQuickLog(){openAddSheet(dpMealNow(),'')}
function dpQuickAdd(id){activeMealKey=dpMealNow();editingLogDate=null;openQtySheet(id)}

function dpOpenEntry(date,meal,index){dpEdit={date,meal,index};const e=STATE.logs[date][meal][index],n=dpNutrition(e);document.getElementById('dp-edit-name').textContent=e.name;document.getElementById('dp-edit-amount').value=e.quantity||e.grams;document.getElementById('dp-edit-meal').value=meal;document.getElementById('dp-edit-summary').textContent=Math.round(n.cal)+' kcal · P '+Math.round(n.p)+'g · C '+Math.round(n.c)+'g · F '+Math.round(n.f)+'g';openSheet('sheet-dp-edit')}
function dpSaveEntry(){const c=dpEdit,e=STATE.logs[c.date][c.meal][c.index],a=Number(document.getElementById('dp-edit-amount').value),m=document.getElementById('dp-edit-meal').value;if(!(a>0)){toast('Enter a valid amount');return}e.quantity=a;e.grams=Math.round(a);e.updatedAt=new Date().toISOString();const n=dpNutrition(e);STATE.logs[c.date][c.meal].splice(c.index,1);STATE.logs[c.date][m].push(n);save();closeSheet('sheet-dp-edit');c.date===todayKey()?renderToday():renderLogDayDetail(c.date);toast('Entry updated')}
function dpDuplicateEntry(){const c=dpEdit,e=JSON.parse(JSON.stringify(STATE.logs[c.date][c.meal][c.index]));e.id=dpId('entry');STATE.logs[c.date][c.meal].push(e);save();closeSheet('sheet-dp-edit');c.date===todayKey()?renderToday():renderLogDayDetail(c.date);toast('Entry duplicated')}
function dpDeleteEntry(){const c=dpEdit;STATE.logs[c.date][c.meal].splice(c.index,1);save();closeSheet('sheet-dp-edit');c.date===todayKey()?renderToday():renderLogDayDetail(c.date);toast('Entry deleted')}
function dpWireEntries(){document.querySelectorAll('#meals-container .entry,#log-day-detail .entry').forEach(el=>{if(el.dataset.dpWired)return;el.dataset.dpWired='1';el.addEventListener('click',ev=>{if(ev.target.closest('.edel'))return;const card=el.closest('.meal-card'),container=card.parentElement,mealIndex=[...container.children].indexOf(card),entryIndex=[...el.parentElement.children].indexOf(el),date=container.id==='meals-container'?todayKey():viewingLogDate;dpOpenEntry(date,MEALS[mealIndex].key,entryIndex)})})}
const observer=new MutationObserver(dpWireEntries);

renderIngredientLibrary=function(){dpOriginalRenderIngredients();document.querySelectorAll('#ingredient-library .ing-row').forEach(r=>{const n=r.querySelector('.iname')?.textContent,i=allIngredients().find(x=>x.name===n);if(!i)return;const b=document.createElement('button');b.className='fav-btn';b.textContent=STATE.favourites.includes(i.id)?'★':'☆';b.onclick=e=>{e.stopPropagation();STATE.favourites=STATE.favourites.includes(i.id)?STATE.favourites.filter(x=>x!==i.id):[...STATE.favourites,i.id];save();renderIngredientLibrary()};r.appendChild(b)})};

renderLog=function(){dpOriginalRenderLog();const h=document.getElementById('dp-trends');if(!h)return;const days=[];for(let x=6;x>=0;x--){const d=new Date();d.setDate(d.getDate()-x);const k=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');days.push({k,...dpTotals(k)})}const logged=days.filter(x=>x.cal),avg=k=>logged.length?logged.reduce((a,x)=>a+x[k],0)/logged.length:0;h.innerHTML='<div class="card"><h3>Nutrition trends</h3><div class="stat-grid"><div class="stat-box"><div class="v">'+Math.round(avg('cal'))+'</div><div class="k">Avg calories</div></div><div class="stat-box"><div class="v">'+Math.round(avg('p'))+'g</div><div class="k">Avg protein</div></div></div><div class="spark-bars">'+days.map(x=>'<i style="height:'+Math.max(3,Math.min(100,x.cal/calcCalorieTarget(STATE.profile)*100))+'%"></i>').join('')+'</div></div>'};
renderProfileScreen=function(){dpOriginalRenderProfile();const h=document.getElementById('dp-profile-extra');if(!h)return;const p=STATE.profile;h.innerHTML='<div class="card"><h3>Custom targets</h3><div class="row2"><div><label>Carbs (g)</label><input id="dp-carb" type="number" value="'+(p.carbTarget||'')+'"></div><div><label>Fat (g)</label><input id="dp-fat" type="number" value="'+(p.fatTarget||'')+'"></div></div><button class="btn" onclick="dpSaveTargets()">Save targets</button></div><div class="card"><h3>Weight history</h3><input id="dp-weight" type="number" step="0.1" placeholder="Weight in kg"><button class="btn top-gap" onclick="dpAddWeight()">Add today’s weight</button></div><div class="card"><h3>App information</h3><p><b>Daily Plate v'+DP_VERSION+'</b><br><span class="helper">Schema '+DP_SCHEMA_VERSION+' · Local-first · Sync-ready data model</span></p><button class="btn ghost" onclick="dpExportCSV()">Export logs as CSV</button></div>'};
function dpSaveTargets(){STATE.profile.carbTarget=Number(document.getElementById('dp-carb').value)||null;STATE.profile.fatTarget=Number(document.getElementById('dp-fat').value)||null;save();renderToday();toast('Targets saved')}
function dpAddWeight(){const v=Number(document.getElementById('dp-weight').value);if(!(v>20&&v<500)){toast('Enter a valid weight');return}STATE.weights=STATE.weights.filter(x=>x.date!==todayKey());STATE.weights.push({id:dpId('weight'),date:todayKey(),value:v});STATE.profile.weight=v;save();renderProfileScreen();toast('Weight recorded')}
function dpExportCSV(){const rows=[['date','meal','food','amount','unit','calories','protein','carbs','fat']];Object.entries(STATE.logs).forEach(([d,day])=>MEALS.forEach(m=>(day[m.key]||[]).forEach(e=>{const n=dpNutrition(e);rows.push([d,m.name,e.name,e.quantity||e.grams,e.unit,n.cal,n.p,n.c,n.f])})));const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='daily-plate-v1.1-logs.csv';a.click();URL.revokeObjectURL(a.href)}

function dpInit(){document.title='Daily Plate v'+DP_VERSION;const g=document.getElementById('today-greeting');if(g&&!document.getElementById('dp-version'))g.insertAdjacentHTML('afterend','<span id="dp-version" class="version-badge">v'+DP_VERSION+'</span>');document.querySelector('#screen-today .card')?.insertAdjacentHTML('afterend','<div id="dp-today-extra"></div>');document.querySelector('#screen-log .day-strip')?.insertAdjacentHTML('afterend','<div id="dp-trends"></div>');document.querySelector('#screen-profile .card:last-of-type')?.insertAdjacentHTML('beforebegin','<div id="dp-profile-extra"></div>');document.getElementById('app').insertAdjacentHTML('beforeend','<div class="sheet-backdrop" id="sheet-dp-edit"><div class="sheet"><div class="sheet-handle"></div><div class="sheet-title" id="dp-edit-name">Edit entry</div><label>Amount (g/ml)</label><input id="dp-edit-amount" type="number"><label>Meal</label><select id="dp-edit-meal">'+MEALS.map(m=>'<option value="'+m.key+'">'+m.name+'</option>').join('')+'</select><p id="dp-edit-summary" class="helper"></p><button class="btn ember" onclick="dpSaveEntry()">Save changes</button><div class="row-actions"><button class="btn ghost" onclick="dpDuplicateEntry()">Duplicate</button><button class="btn ghost danger" onclick="dpDeleteEntry()">Delete</button></div></div></div>');observer.observe(document.getElementById('app'),{subtree:true,childList:true});if(STATE.profile){renderToday();renderLog();renderProfileScreen()}dpWireEntries()}
window.addEventListener('load',()=>setTimeout(dpInit,50));
