/* Daily Plate v1.2 feature update */
const V12_VERSION='1.2';
let v12Edit=null;
const v12OldSwitch=switchTab,v12OldToday=renderToday,v12OldLog=renderLog,v12OldProfile=renderProfileScreen,v12OldSaveIngredient=saveIngredientEditor,v12OldDeleteIngredient=deleteIngredientEditor;
function v12Total(k){const o={cal:0,p:0,c:0,f:0},d=STATE.logs[k];if(!d)return o;MEALS.forEach(m=>(d[m.key]||[]).forEach(e=>{const n=dpNutrition(e);o.cal+=+n.cal||0;o.p+=+n.p||0;o.c+=+n.c||0;o.f+=+n.f||0}));return o}
function v12Days(){const a=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');a.push({k,d,...v12Total(k)})}return a}
function renderHome(){if(!STATE.profile)return;Object.values(STATE.logs||{}).forEach(d=>MEALS.forEach(m=>(d[m.key]||[]).forEach((e,n)=>d[m.key][n]=dpNutrition(e))));const days=v12Days(),logged=days.filter(x=>x.cal>0),avg=k=>logged.length?logged.reduce((a,x)=>a+x[k],0)/logged.length:0,target=calcCalorieTarget(STATE.profile),hit=logged.filter(x=>Math.abs(x.cal-target)<=target*.01).length,pct=logged.length?Math.round(hit/logged.length*100):0,max=Math.max(target,...days.map(x=>x.cal));document.getElementById('home-date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();document.getElementById('home-dashboard').innerHTML=`<div class="home-hero card"><div><span class="dashboard-label">7-day overview</span><strong>${logged.length}</strong><small>logged days</small></div><div class="home-target"><span>${pct}%</span><small>target adherence</small></div></div><div class="card"><h3>Calories — last 7 days</h3><div class="weekbar">${days.map(x=>`<div class="col"><div class="bar-cal-label">${x.cal?Math.round(x.cal):''}</div><div class="bar ${x.cal>target?'over-target':''}" style="height:${x.cal?Math.max(x.cal/max*76,6):3}px"></div><div class="lbl ${x.k===todayKey()?'lbl-today':''}">${x.d.toLocaleDateString(undefined,{weekday:'narrow'})}</div></div>`).join('')}</div></div><div class="card"><h3>7-day average</h3><p class="dashboard-helper">Average across logged days only</p><div class="dashboard-grid"><div><strong>${Math.round(avg('cal'))}</strong><span>Calories</span></div><div><strong>${Math.round(avg('p'))}g</strong><span>Protein</span></div><div><strong>${Math.round(avg('c'))}g</strong><span>Carbs</span></div><div><strong>${Math.round(avg('f'))}g</strong><span>Fat</span></div></div></div><div class="card adherence-card"><div class="adherence-ring" style="--p:${pct}"><div><strong>${pct}%</strong><span>adherence</span></div></div><div><h3>Target adherence</h3><p>${hit} of ${logged.length} logged days within target</p><small>Within ±1% of ${target} kcal</small></div></div>`}
switchTab=function(id){if(id==='screen-home'){goTo(id);document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));renderHome()}else v12OldSwitch(id)};
initMainApp=function(){document.getElementById('tabbar').style.display='flex';goTo('screen-home');document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab==='screen-home'));renderHome();setInterval(tickClock,15000);tickClock()};
renderToday=function(){v12OldToday();const h=document.getElementById('dp-today-extra');if(h){const ids=[...STATE.favourites,...STATE.recentIngredients].filter((x,n,a)=>a.indexOf(x)===n).slice(0,6);h.innerHTML=`<div class="section-title">Quick add</div><div class="quick-chips">${ids.map(id=>{const i=findIngredient(id);return i&&!i.hidden?`<button onclick="v12Quick('${id}')">${dpEscape(i.name)}</button>`:''}).join('')||'<span class="empty-hint">Recent and favourite foods appear here.</span>'}</div>`}}
function v12Quick(id){activeIngredientForQty=id;openSheet('sheet-v12-meal')}
function v12QuickContinue(){activeMealKey=document.getElementById('v12-meal').value;editingLogDate=null;closeSheet('sheet-v12-meal');openQtySheet(activeIngredientForQty)}
function v12RenderLogDay(k){const host=document.getElementById('log-day-detail'),day=getDayLog(k),isToday=k===todayKey(),editable=k===tomorrowKey()||(k<todayKey()&&logEditMode);host.innerHTML=isToday?'<div class="log-readonly-notice">Add using Today Tab</div>':'';MEALS.forEach(m=>{const es=day[m.key]||[],card=document.createElement('div');card.className='card meal-card';card.innerHTML=`<div class="meal-head"><div class="left"><div class="meal-icon">${m.icon}</div><div><div class="meal-name">${m.name}</div><div class="meal-cals">${Math.round(es.reduce((a,e)=>a+dpNutrition(e).cal,0))} kcal</div></div></div>${editable?`<button class="add-btn" onclick="openAddSheet('${m.key}','${k}')">+</button>`:''}</div><div class="entry-list">${es.length?es.map((raw,n)=>{const e=dpNutrition(raw);return `<div class="entry ${editable?'entry-editable':''}" ${editable?`onclick="v12OpenEdit('${k}','${m.key}',${n})"`:''}><div><div class="ename">${dpEscape(e.name)}</div><div class="emeta">${e.grams}${e.unit||'g'} · P${Math.round(e.p)} C${Math.round(e.c)} F${Math.round(e.f)}</div></div><div class="ecal">${Math.round(e.cal)}</div></div>`}).join(''):`<div class="empty-hint">${editable?'Tap + to add food':'Nothing logged'}</div>`}</div>`;host.appendChild(card)})}
renderLogDayDetail=v12RenderLogDay;
renderWeekBar=function(){};
renderLog=function(){v12OldLog();const trend=document.getElementById('dp-trends');if(trend)trend.remove();const p=document.getElementById('log-date-picker');if(p){p.max=tomorrowKey();p.value=viewingLogDate||todayKey()}v12RenderLogDay(viewingLogDate||todayKey())};
function v12PickDate(v){if(!v)return;if(v>tomorrowKey()){toast('Only tomorrow can be planned');return}viewingLogDate=v;logEditMode=v===tomorrowKey();renderLog()}
function v12OpenEdit(date,meal,index){if(date===todayKey()&&document.getElementById('screen-log').classList.contains('active'))return;v12Edit={date,meal,index};const e=STATE.logs[date][meal][index],i=findIngredient(e.ingredientId);document.getElementById('v12-edit-name').textContent=i?.name||e.name;document.getElementById('v12-amount').value=e.quantity||e.grams;const w=document.getElementById('v12-count-wrap');if(i?.uw&&!i.isLiquid){w.style.display='';document.getElementById('v12-count').value=e.count||Math.max(1,Math.round((e.quantity||e.grams)/i.uw))}else w.style.display='none';v12Preview();openSheet('sheet-v12-edit')}
function v12Preview(){if(!v12Edit)return;const e=STATE.logs[v12Edit.date][v12Edit.meal][v12Edit.index],i=findIngredient(e.ingredientId),a=+document.getElementById('v12-amount').value||0,x=a/100;document.getElementById('v12-summary').textContent=i?`${Math.round(i.cal*x)} kcal · P ${Math.round(i.p*x)}g · C ${Math.round(i.c*x)}g · F ${Math.round(i.f*x)}g`:''}
function v12Count(){const e=STATE.logs[v12Edit.date][v12Edit.meal][v12Edit.index],i=findIngredient(e.ingredientId),c=Math.max(1,+document.getElementById('v12-count').value||1);if(i?.uw){document.getElementById('v12-amount').value=Math.round(c*i.uw);v12Preview()}}
function v12SaveEntry(){const c=v12Edit,e=STATE.logs[c.date][c.meal][c.index],i=findIngredient(e.ingredientId),a=+document.getElementById('v12-amount').value;if(!(a>0)){toast('Enter a valid amount');return}e.quantity=a;e.grams=Math.round(a);e.count=i?.uw&&!i.isLiquid?Math.max(1,+document.getElementById('v12-count').value||1):null;STATE.logs[c.date][c.meal][c.index]=dpNutrition(e);save();closeSheet('sheet-v12-edit');c.date===todayKey()?renderToday():renderLog();renderHome();toast('Entry updated')}
function v12DeleteEntry(){const c=v12Edit;STATE.logs[c.date][c.meal].splice(c.index,1);save();closeSheet('sheet-v12-edit');c.date===todayKey()?renderToday():renderLog();renderHome();toast('Entry deleted')}
function v12WireToday(){document.querySelectorAll('#meals-container .entry').forEach(el=>{if(el.dataset.v12)return;el.dataset.v12='1';el.addEventListener('click',ev=>{if(ev.target.closest('.edel'))return;const card=el.closest('.meal-card'),mi=[...document.getElementById('meals-container').children].indexOf(card),ei=[...el.parentElement.children].indexOf(el);v12OpenEdit(todayKey(),MEALS[mi].key,ei)})})}
const v12Observer=new MutationObserver(v12WireToday);
saveIngredientEditor=function(){const id=activeEditingIngredientId;if(!id){v12OldSaveIngredient();return}const old=findIngredient(id),data={id,name:document.getElementById('ie-name').value.trim(),cat:document.getElementById('ie-cat').value.trim()||'Custom',cal:+document.getElementById('ie-cal').value||0,p:+document.getElementById('ie-protein').value||0,c:+document.getElementById('ie-carb').value||0,f:+document.getElementById('ie-fat').value||0,sugar:+document.getElementById('ie-sugar').value||0,fiber:+document.getElementById('ie-fiber').value||0,sodium:+document.getElementById('ie-sodium').value||0,defaultServing:+document.getElementById('ie-default-serving').value||100,isLiquid:isLiquidToggleOn,basis:isLiquidToggleOn?'100ml':'100g',uw:old?.uw,unit:old?.unit};const n=STATE.customIngredients.findIndex(x=>x.id===id);if(n>=0)STATE.customIngredients[n]=data;else STATE.customIngredients.push(data);STATE.deletedBuiltins=STATE.deletedBuiltins.filter(x=>x!==id);Object.values(STATE.logs).forEach(d=>MEALS.forEach(m=>(d[m.key]||[]).forEach((e,x)=>d[m.key][x]=dpNutrition(e))));save();closeSheet('sheet-ing-edit');renderIngredientLibrary();renderToday();renderHome();if(document.getElementById('screen-log').classList.contains('active'))renderLog();toast('Ingredient updated throughout app')};
deleteIngredientEditor=function(){const id=activeEditingIngredientId;if(!id)return;STATE.archivedIngredients=STATE.archivedIngredients||[];const i=findIngredient(id);if(i&&!STATE.archivedIngredients.some(x=>x.id===id))STATE.archivedIngredients.push({...i,hidden:true});STATE.customIngredients=STATE.customIngredients.filter(x=>x.id!==id);if(!STATE.deletedBuiltins.includes(id))STATE.deletedBuiltins.push(id);save();closeSheet('sheet-ing-edit');renderIngredientLibrary();toast('Ingredient hidden from future use')};
const v12OldFind=findIngredient,v12OldAll=allIngredients;
findIngredient=function(id){return v12OldFind(id)||(STATE.archivedIngredients||[]).find(x=>x.id===id)};
allIngredients=function(){return v12OldAll().filter(x=>!x.hidden)};
renderProfileScreen=function(){v12OldProfile();const h=document.getElementById('dp-profile-extra');if(h)h.innerHTML=`<div class="card"><h3>App information</h3><p><b>Daily Plate v${V12_VERSION}</b><br><span class="helper">Schema 5 · Local-first · Sync-ready data model</span></p></div>`};
function v12Init(){document.title='Daily Plate v1.2';document.querySelector('#dp-version')?.remove();document.querySelector('#dp-trends')?.remove();const t=document.getElementById('meals-container');v12Observer.observe(t,{childList:true,subtree:true});if(STATE.profile){renderHome();renderToday();renderProfileScreen()}v12WireToday()}
window.addEventListener('load',()=>setTimeout(v12Init,120));
