/* Daily Plate v1.3 - dashboard and shared header */
const V13_VERSION='1.3';
let v13Edit=null;
const v13BaseSwitch=switchTab;
const v13BaseToday=renderToday;
const v13BaseLog=renderLog;
const v13BaseProfile=renderProfileScreen;
const v13BaseSaveIngredient=saveIngredientEditor;
const v13BaseDeleteIngredient=deleteIngredientEditor;
const v13BaseFindIngredient=findIngredient;
const v13BaseAllIngredients=allIngredients;

function v13TabLabel(id){return ({'screen-home':'Home','screen-today':'Today','screen-log':'Log','screen-ingredients':'Ingredients','screen-profile':'Profile'})[id]||'Daily Plate';}
function v13SetHeader(id){const el=document.getElementById('app-tab-name');if(el)el.textContent=v13TabLabel(id);}
function v13Totals(key){const o={cal:0,p:0,c:0,f:0},day=STATE.logs[key];if(!day)return o;MEALS.forEach(m=>(day[m.key]||[]).forEach(e=>{const n=dpNutrition(e);o.cal+=Number(n.cal)||0;o.p+=Number(n.p)||0;o.c+=Number(n.c)||0;o.f+=Number(n.f)||0;}));return o;}
function v13DateKey(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function v13Days(count){const out=[];for(let i=count-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=v13DateKey(d);out.push({k,d,...v13Totals(k)});}return out;}
function v13MacroTargets(){const cal=calcCalorieTarget(STATE.profile);return {cal,p:calcProteinTarget(STATE.profile),c:STATE.profile.carbTarget||Math.round(cal*.45/4),f:STATE.profile.fatTarget||Math.round(cal*.27/9)};}
function v13Ring(label,value,target,color){const pct=target?Math.round(value/target*100):0,cap=Math.max(0,Math.min(100,pct));return `<div class="avg-tile"><div class="avg-ring" style="--ring:${cap};--ring-color:${color}"><div><strong>${Math.round(value)}${label==='Calories'?'':'g'}</strong><small>${pct}%</small></div></div><span>${label}</span><em>Target ${Math.round(target)}${label==='Calories'?' kcal':'g'}</em></div>`;}
function renderHome(){if(!STATE.profile)return;v13RefreshEntries();const days30=v13Days(30),logged=days30.filter(x=>x.cal>0),avg=k=>logged.length?logged.reduce((a,x)=>a+x[k],0)/logged.length:0,t=v13MacroTargets();document.getElementById('home-greeting').textContent='Hello, '+STATE.profile.name;document.getElementById('home-dashboard').innerHTML=`<div class="card overview-card"><div class="card-heading-row"><div><h3>30-Day Overview</h3><p>Swipe horizontally to view earlier days</p></div><span>${logged.length} logged</span></div><div class="overview-scroll" id="overview-scroll"><div class="overview-track">${days30.map(x=>{const pct=t.cal?Math.min(120,x.cal/t.cal*100):0;return `<div class="overview-day"><div class="overview-cal">${x.cal?Math.round(x.cal):'—'}</div><div class="overview-bar-wrap"><i class="${x.cal>t.cal?'over':''}" style="height:${x.cal?Math.max(5,pct*.72):3}px"></i></div><b>${x.d.toLocaleDateString(undefined,{weekday:'narrow'})}</b><small>${x.d.getDate()}</small></div>`;}).join('')}</div></div></div><div class="card"><div class="card-heading-row"><div><h3>30-Day Average</h3><p>Based on ${logged.length} logged day${logged.length===1?'':'s'}</p></div></div><div class="avg-ring-grid">${v13Ring('Calories',avg('cal'),t.cal,'#E8643A')}${v13Ring('Protein',avg('p'),t.p,'#7FA37E')}${v13Ring('Carbs',avg('c'),t.c,'#C9A227')}${v13Ring('Fat',avg('f'),t.f,'#2F6F8F')}</div></div>`;requestAnimationFrame(()=>{const sc=document.getElementById('overview-scroll');if(sc)sc.scrollLeft=sc.scrollWidth;});}

switchTab=function(id){v13SetHeader(id);if(id==='screen-home'){goTo(id);document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));renderHome();}else v13BaseSwitch(id);};
initMainApp=function(){document.getElementById('tabbar').style.display='flex';goTo('screen-home');document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab==='screen-home'));v13SetHeader('screen-home');renderHome();setInterval(tickClock,15000);tickClock();};

function v13RefreshEntries(){Object.values(STATE.logs||{}).forEach(d=>MEALS.forEach(m=>(d[m.key]||[]).forEach((e,n)=>d[m.key][n]=dpNutrition(e))));}
renderToday=function(){v13RefreshEntries();v13BaseToday();document.getElementById('today-greeting').textContent='';const extra=document.getElementById('dp-today-extra');if(extra){const ids=[...STATE.favourites,...STATE.recentIngredients].filter((x,n,a)=>a.indexOf(x)===n).slice(0,6);extra.innerHTML=`<div class="section-title">Quick add</div><div class="quick-chips">${ids.map(id=>{const i=findIngredient(id);return i&&!i.hidden?`<button onclick="v13Quick('${id}')">${dpEscape(i.name)}</button>`:''}).join('')||'<span class="empty-hint">Recent and favourite foods appear here.</span>'}</div>`;}};
function v13Quick(id){activeIngredientForQty=id;openSheet('sheet-v13-meal');}
function v13QuickContinue(){activeMealKey=document.getElementById('v13-meal').value;editingLogDate=null;closeSheet('sheet-v13-meal');openQtySheet(activeIngredientForQty);}

function v13RenderLogDay(key){const host=document.getElementById('log-day-detail'),day=getDayLog(key),isToday=key===todayKey(),editable=key===tomorrowKey()||(key<todayKey()&&logEditMode);host.innerHTML=isToday?'<div class="log-readonly-notice">Add using Today Tab</div>':'';MEALS.forEach(m=>{const entries=day[m.key]||[],card=document.createElement('div');card.className='card meal-card';card.innerHTML=`<div class="meal-head"><div class="left"><div class="meal-icon">${m.icon}</div><div><div class="meal-name">${m.name}</div><div class="meal-cals">${Math.round(entries.reduce((a,e)=>a+dpNutrition(e).cal,0))} kcal</div></div></div>${editable?`<button class="add-btn" onclick="openAddSheet('${m.key}','${key}')">+</button>`:''}</div><div class="entry-list">${entries.length?entries.map((raw,n)=>{const e=dpNutrition(raw);return `<div class="entry ${editable?'entry-editable':''}" ${editable?`onclick="v13OpenEdit('${key}','${m.key}',${n})"`:''}><div><div class="ename">${dpEscape(e.name)}</div><div class="emeta">${e.grams}${e.unit||'g'} · P${Math.round(e.p)} C${Math.round(e.c)} F${Math.round(e.f)}</div></div><div class="ecal">${Math.round(e.cal)}</div></div>`;}).join(''):`<div class="empty-hint">${editable?'Tap + to add food':'Nothing logged'}</div>`}</div>`;host.appendChild(card);});}
renderLogDayDetail=v13RenderLogDay;
renderWeekBar=function(){};
renderLog=function(){v13RefreshEntries();v13BaseLog();document.getElementById('dp-trends')?.remove();const p=document.getElementById('log-date-picker');if(p){p.max=tomorrowKey();p.value=viewingLogDate||todayKey();}v13RenderLogDay(viewingLogDate||todayKey());};
function v13SelectDate(v){if(!v)return;if(v>tomorrowKey()){toast('Only tomorrow can be planned');return;}viewingLogDate=v;logEditMode=v===tomorrowKey();renderLog();}
function v13OpenEdit(date,meal,index){if(date===todayKey()&&document.getElementById('screen-log').classList.contains('active'))return;v13Edit={date,meal,index};const e=STATE.logs[date][meal][index],i=findIngredient(e.ingredientId);document.getElementById('v13-edit-name').textContent=i?.name||e.name;document.getElementById('v13-amount').value=e.quantity||e.grams;const w=document.getElementById('v13-count-wrap');if(i?.uw&&!i.isLiquid){w.style.display='';document.getElementById('v13-count').value=e.count||Math.max(1,Math.round((e.quantity||e.grams)/i.uw));}else w.style.display='none';v13Preview();openSheet('sheet-v13-edit');}
function v13Preview(){if(!v13Edit)return;const e=STATE.logs[v13Edit.date][v13Edit.meal][v13Edit.index],i=findIngredient(e.ingredientId),a=Number(document.getElementById('v13-amount').value)||0,x=a/100;document.getElementById('v13-summary').textContent=i?`${Math.round(i.cal*x)} kcal · P ${Math.round(i.p*x)}g · C ${Math.round(i.c*x)}g · F ${Math.round(i.f*x)}g`:'';}
function v13CountChanged(){const e=STATE.logs[v13Edit.date][v13Edit.meal][v13Edit.index],i=findIngredient(e.ingredientId),c=Math.max(1,Number(document.getElementById('v13-count').value)||1);if(i?.uw){document.getElementById('v13-amount').value=Math.round(c*i.uw);v13Preview();}}
function v13SaveEntry(){const c=v13Edit,e=STATE.logs[c.date][c.meal][c.index],i=findIngredient(e.ingredientId),a=Number(document.getElementById('v13-amount').value);if(!(a>0)){toast('Enter a valid amount');return;}e.quantity=a;e.grams=Math.round(a);e.count=i?.uw&&!i.isLiquid?Math.max(1,Number(document.getElementById('v13-count').value)||1):null;STATE.logs[c.date][c.meal][c.index]=dpNutrition(e);save();closeSheet('sheet-v13-edit');c.date===todayKey()?renderToday():renderLog();renderHome();toast('Entry updated');}
function v13DeleteEntry(){const c=v13Edit;STATE.logs[c.date][c.meal].splice(c.index,1);save();closeSheet('sheet-v13-edit');c.date===todayKey()?renderToday():renderLog();renderHome();toast('Entry deleted');}
function v13WireToday(){document.querySelectorAll('#meals-container .entry').forEach(el=>{if(el.dataset.v13)return;el.dataset.v13='1';el.addEventListener('click',ev=>{if(ev.target.closest('.edel'))return;const card=el.closest('.meal-card'),mi=[...document.getElementById('meals-container').children].indexOf(card),ei=[...el.parentElement.children].indexOf(el);v13OpenEdit(todayKey(),MEALS[mi].key,ei);});});}
const v13Observer=new MutationObserver(v13WireToday);

findIngredient=function(id){return v13BaseFindIngredient(id)||(STATE.archivedIngredients||[]).find(x=>x.id===id);};
allIngredients=function(){return v13BaseAllIngredients().filter(x=>!x.hidden);};
saveIngredientEditor=function(){const id=activeEditingIngredientId;if(!id){v13BaseSaveIngredient();return;}const old=findIngredient(id),data={id,name:document.getElementById('ie-name').value.trim(),cat:document.getElementById('ie-cat').value.trim()||'Custom',cal:Number(document.getElementById('ie-cal').value)||0,p:Number(document.getElementById('ie-protein').value)||0,c:Number(document.getElementById('ie-carb').value)||0,f:Number(document.getElementById('ie-fat').value)||0,sugar:Number(document.getElementById('ie-sugar').value)||0,fiber:Number(document.getElementById('ie-fiber').value)||0,sodium:Number(document.getElementById('ie-sodium').value)||0,defaultServing:Number(document.getElementById('ie-default-serving').value)||100,isLiquid:isLiquidToggleOn,basis:isLiquidToggleOn?'100ml':'100g',uw:old?.uw,unit:old?.unit};const n=STATE.customIngredients.findIndex(x=>x.id===id);if(n>=0)STATE.customIngredients[n]=data;else STATE.customIngredients.push(data);STATE.deletedBuiltins=STATE.deletedBuiltins.filter(x=>x!==id);v13RefreshEntries();save();closeSheet('sheet-ing-edit');renderIngredientLibrary();renderToday();renderHome();if(document.getElementById('screen-log').classList.contains('active'))renderLog();toast('Ingredient updated throughout app');};
deleteIngredientEditor=function(){const id=activeEditingIngredientId;if(!id)return;STATE.archivedIngredients=STATE.archivedIngredients||[];const i=findIngredient(id);if(i&&!STATE.archivedIngredients.some(x=>x.id===id))STATE.archivedIngredients.push({...i,hidden:true});STATE.customIngredients=STATE.customIngredients.filter(x=>x.id!==id);if(!STATE.deletedBuiltins.includes(id))STATE.deletedBuiltins.push(id);save();closeSheet('sheet-ing-edit');renderIngredientLibrary();toast('Ingredient hidden from future use');};
renderProfileScreen=function(){v13BaseProfile();const h=document.getElementById('dp-profile-extra');if(h)h.innerHTML=`<div class="card"><h3>App information</h3><p><b>Daily Plate v${V13_VERSION}</b><br><span class="helper">Schema 5 · Local-first · Sync-ready data model</span></p></div>`;};

function v13Init(){document.title='Daily Plate v1.3';document.querySelector('#dp-version')?.remove();document.querySelector('#dp-trends')?.remove();v13Observer.observe(document.getElementById('meals-container'),{childList:true,subtree:true});if(STATE.profile){v13SetHeader('screen-home');renderHome();renderToday();renderProfileScreen();}v13WireToday();}
window.addEventListener('load',()=>setTimeout(v13Init,130));
