/* Daily Plate v1.4 - streamlined headers and log editing */
const V14_VERSION='1.4';
let v14Edit=null;
let v14Undo=null;
let v14EditDayAuthorized=false;
let v14LastLogDate=null;
const v14BaseHome=renderHome;
const v14BaseToday=renderToday;
const v14BaseLog=renderLog;
const v14BaseProfile=renderProfileScreen;

function v14Totals(key){const out={cal:0,p:0,c:0,f:0},day=STATE.logs[key];if(!day)return out;MEALS.forEach(m=>(day[m.key]||[]).forEach(raw=>{const e=dpNutrition(raw);out.cal+=Number(e.cal)||0;out.p+=Number(e.p)||0;out.c+=Number(e.c)||0;out.f+=Number(e.f)||0;}));return out;}
function v14Days(count){const out=[];for(let i=count-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');out.push({k,d,...v14Totals(k)});}return out;}
function v14Targets(){const cal=calcCalorieTarget(STATE.profile);return {cal,p:calcProteinTarget(STATE.profile),c:STATE.profile.carbTarget||Math.round(cal*.45/4),f:STATE.profile.fatTarget||Math.round(cal*.27/9)};}
function v14Ring(label,value,target,color){const pct=target?Math.round(value/target*100):0,cap=Math.max(0,Math.min(100,pct));return `<div class="avg-tile"><div class="avg-ring" style="--ring:${cap};--ring-color:${color}"><div><strong>${Math.round(value)}${label==='Calories'?'':'g'}</strong><small>${pct}%</small></div></div><span>${label}</span><em>Target ${Math.round(target)}${label==='Calories'?' kcal':'g'}</em></div>`;}
renderHome=function(){if(!STATE.profile)return;v13RefreshEntries();const days=v14Days(30),logged=days.filter(x=>x.cal>0),avg=k=>logged.length?logged.reduce((a,x)=>a+x[k],0)/logged.length:0,t=v14Targets();document.getElementById('home-greeting').textContent='Hello, '+STATE.profile.name;document.getElementById('home-dashboard').innerHTML=`<div class="card overview-card"><h3>30 Days Calorie Count</h3><div class="overview-scroll" id="overview-scroll"><div class="overview-track">${days.map(x=>{const pct=t.cal?Math.min(120,x.cal/t.cal*100):0;return `<div class="overview-day"><div class="overview-cal">${x.cal?Math.round(x.cal):'—'}</div><div class="overview-bar-wrap"><i class="${x.cal>t.cal?'over':''}" style="height:${x.cal?Math.max(5,pct*.72):3}px"></i></div><b>${x.d.toLocaleDateString(undefined,{weekday:'narrow'})}</b><small>${x.d.getDate()}</small></div>`;}).join('')}</div></div></div><div class="card"><h3>30 Day Macros Average</h3><div class="avg-ring-grid">${v14Ring('Calories',avg('cal'),t.cal,'#E8643A')}${v14Ring('Protein',avg('p'),t.p,'#7FA37E')}${v14Ring('Carbs',avg('c'),t.c,'#C9A227')}${v14Ring('Fat',avg('f'),t.f,'#2F6F8F')}</div></div>`;requestAnimationFrame(()=>{const sc=document.getElementById('overview-scroll');if(sc)sc.scrollLeft=sc.scrollWidth;});};

function v14OpenEdit(date,meal,index){if(document.getElementById('screen-log').classList.contains('active')&&!v14EditDayAuthorized)return;v14Edit={date,meal,index};const e=STATE.logs[date][meal][index],i=findIngredient(e.ingredientId);document.getElementById('v14-edit-name').textContent=i?.name||e.name;document.getElementById('v14-amount').value=e.quantity||e.grams;const wrap=document.getElementById('v14-count-wrap');if(i?.uw&&!i.isLiquid){wrap.style.display='';document.getElementById('v14-count').value=e.count||Math.max(1,Math.round((e.quantity||e.grams)/i.uw));}else wrap.style.display='none';v14Preview();openSheet('sheet-v14-edit');}
// Route every legacy entry-tap handler to the v1.4 editor.
// v1.1 and v1.3 attached addEventListener handlers before v1.4 loaded; those
// handlers resolve these global function names at click time.
dpOpenEntry=function(date,meal,index){v14OpenEdit(date,meal,index);};
v13OpenEdit=function(date,meal,index){v14OpenEdit(date,meal,index);};

function v14Preview(){if(!v14Edit)return;const e=STATE.logs[v14Edit.date][v14Edit.meal][v14Edit.index],i=findIngredient(e.ingredientId),amount=Number(document.getElementById('v14-amount').value)||0,x=amount/100;document.getElementById('v14-summary').textContent=i?`${Math.round(i.cal*x)} kcal · P ${Math.round(i.p*x)}g · C ${Math.round(i.c*x)}g · F ${Math.round(i.f*x)}g`:'';}
function v14CountChanged(){const e=STATE.logs[v14Edit.date][v14Edit.meal][v14Edit.index],i=findIngredient(e.ingredientId),count=Math.max(1,Number(document.getElementById('v14-count').value)||1);if(i?.uw){document.getElementById('v14-amount').value=Math.round(count*i.uw);v14Preview();}}
function v14SaveEntry(){const c=v14Edit,e=STATE.logs[c.date][c.meal][c.index],i=findIngredient(e.ingredientId),amount=Number(document.getElementById('v14-amount').value);if(!(amount>0)){toast('Enter a valid amount');return;}e.quantity=amount;e.grams=Math.round(amount);e.count=i?.uw&&!i.isLiquid?Math.max(1,Number(document.getElementById('v14-count').value)||1):null;e.updatedAt=new Date().toISOString();STATE.logs[c.date][c.meal][c.index]=dpNutrition(e);save();closeSheet('sheet-v14-edit');c.date===todayKey()?renderToday():renderLog();renderHome();toast('Entry updated');}
function v14Delete(date,meal,index){const removed=STATE.logs[date][meal].splice(index,1)[0];v14Undo={date,meal,index,entry:removed};save();date===todayKey()?renderToday():renderLog();renderHome();const t=document.getElementById('toast');t.textContent='Deleted · Undo';t.classList.add('show','undo-ready');t.style.pointerEvents='auto';t.onclick=v14UndoDelete;clearTimeout(window.v14ToastTimer);window.v14ToastTimer=setTimeout(()=>{t.classList.remove('show','undo-ready');t.style.pointerEvents='none';t.onclick=null;v14Undo=null;},3500);}
function v14UndoDelete(){if(!v14Undo)return;const u=v14Undo;STATE.logs[u.date][u.meal].splice(u.index,0,u.entry);save();u.date===todayKey()?renderToday():renderLog();renderHome();v14Undo=null;const t=document.getElementById('toast');t.style.pointerEvents='none';t.onclick=null;toast('Restored');}

function v14LogSummary(key){const totals=v14Totals(key);return `<div class="log-daily-summary"><div class="daily-calorie"><strong>${Math.round(totals.cal)}</strong><span>kcal</span></div><div class="daily-macros"><div class="sum-protein"><b>${Math.round(totals.p)}g</b><span>Protein</span></div><div class="sum-carbs"><b>${Math.round(totals.c)}g</b><span>Carbs</span></div><div class="sum-fat"><b>${Math.round(totals.f)}g</b><span>Fat</span></div></div></div>`;}
function v14RenderLogDay(key){const host=document.getElementById('log-day-detail'),day=getDayLog(key),isToday=key===todayKey(),editable=!isToday&&v14EditDayAuthorized;host.innerHTML=isToday?'<div class="log-readonly-notice">Add using Today Tab</div>':'';MEALS.forEach(m=>{const entries=day[m.key]||[],card=document.createElement('div');card.className='card meal-card';card.innerHTML=`<div class="meal-head"><div class="left"><div class="meal-icon">${m.icon}</div><div><div class="meal-name">${m.name}</div><div class="meal-cals">${Math.round(entries.reduce((a,e)=>a+dpNutrition(e).cal,0))} kcal</div></div></div>${editable?`<button class="add-btn" onclick="openAddSheet('${m.key}','${key}')">+</button>`:''}</div><div class="entry-list">${entries.length?entries.map((raw,n)=>{const e=dpNutrition(raw);return `<div class="entry ${editable?'entry-editable':''}" ${editable?`onclick="v14OpenEdit('${key}','${m.key}',${n})"`:''}><div><div class="ename">${dpEscape(e.name)}</div><div class="emeta">${e.grams}${e.unit||'g'} · P${Math.round(e.p)} C${Math.round(e.c)} F${Math.round(e.f)}</div></div><div class="eright"><div class="ecal">${Math.round(e.cal)}</div>${editable?`<button class="edel" onclick="event.stopPropagation();v14Delete('${key}','${m.key}',${n})" aria-label="Delete">✕</button>`:''}</div></div>`;}).join(''):`<div class="empty-hint">${editable?'Tap + to add food':'Nothing logged'}</div>`}</div>`;host.appendChild(card);});}
renderLogDayDetail=v14RenderLogDay;
renderLog=function(){const requestedKey=viewingLogDate||todayKey();if(v14LastLogDate!==requestedKey){v14EditDayAuthorized=false;logEditMode=false;v14LastLogDate=requestedKey;}v13RefreshEntries();v14BaseLog();document.getElementById('dp-trends')?.remove();const key=viewingLogDate||todayKey(),picker=document.getElementById('log-date-picker');if(picker){picker.max=tomorrowKey();picker.value=key;}const title=document.getElementById('log-day-title');if(title){document.getElementById('log-daily-summary')?.remove();title.insertAdjacentHTML('afterend',`<div id="log-daily-summary">${v14LogSummary(key)}</div>`);}const edit=document.getElementById('log-edit-btn');if(key===todayKey()){v14EditDayAuthorized=false;logEditMode=false;edit.style.display='none';}else{edit.style.display='';edit.classList.toggle('active',v14EditDayAuthorized);edit.innerHTML=v14EditDayAuthorized?'Done Editing':'Edit Day';}v14RenderLogDay(key);};
toggleLogEdit=function(){if((viewingLogDate||todayKey())===todayKey())return;v14EditDayAuthorized=!v14EditDayAuthorized;logEditMode=v14EditDayAuthorized;renderLog();};
function v13SelectDate(v){if(!v)return;if(v>tomorrowKey()){toast('Only tomorrow can be planned');return;}viewingLogDate=v;v14EditDayAuthorized=false;logEditMode=false;v14LastLogDate=v;renderLog();}

renderToday=function(){v14BaseToday();v14WireToday();};
function v14WireToday(){document.querySelectorAll('#meals-container .entry').forEach((el)=>{if(el.dataset.v14)return;el.dataset.v14='1';el.onclick=(ev)=>{if(ev.target.closest('.edel'))return;const card=el.closest('.meal-card'),mealIndex=[...document.getElementById('meals-container').children].indexOf(card),index=[...el.parentElement.children].indexOf(el);v14OpenEdit(todayKey(),MEALS[mealIndex].key,index);};const old=el.querySelector('.edel');if(old){const card=el.closest('.meal-card'),mealIndex=[...document.getElementById('meals-container').children].indexOf(card),index=[...el.parentElement.children].indexOf(el);old.setAttribute('onclick',`event.stopPropagation();v14Delete('${todayKey()}','${MEALS[mealIndex].key}',${index})`);}});}
const v14Observer=new MutationObserver(v14WireToday);

renderProfileScreen=function(){v14BaseProfile();const h=document.getElementById('dp-profile-extra');if(h)h.innerHTML=`<div class="card"><h3>App information</h3><p><b>Daily Plate v${V14_VERSION}</b><br><span class="helper">Schema 5 · Local-first · Sync-ready data model</span></p></div>`;};
function v14Init(){document.title='Daily Plate v1.4';document.querySelector('.app-header')?.remove();document.querySelectorAll('.app-tab-name').forEach(x=>x.remove());document.querySelector('.add-ingredient-primary')?.remove();document.querySelector('#dp-version')?.remove();document.querySelector('#dp-trends')?.remove();document.getElementById('sheet-dp-edit')?.remove();document.getElementById('sheet-v13-edit')?.remove();v14Observer.observe(document.getElementById('meals-container'),{childList:true,subtree:true});if(STATE.profile){renderHome();renderToday();renderProfileScreen();}v14WireToday();}
window.addEventListener('load',()=>setTimeout(v14Init,170));
